# -*- coding: utf-8 -*-
"""bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ICnDPNG4o-7TJzjlzFb3mQ7R2Hm_NAH """



# bot.py

import os
import asyncio
from telegram import Bot
from apscheduler.schedulers.asyncio import AsyncIOScheduler
import pytz
from threading import Thread
from flask import Flask

# Sozlamalar
BOT_TOKEN = "7634842711:AAFa8U3t0x3YYulaty4grX560JyAsBi7re4"  # o'zingizning tokeningiz
CHANNEL_ID = "@servicyozyovon"  # kanal usernameni kiriting
TIMEZONE = pytz.timezone('Asia/Tashkent')

# Flask server
app = Flask(__name__)

@app.route('/')
def home():
    return "Bot ishlayapti (Render Flask)"

def run():
    port = int(os.environ.get("PORT", 5000))  # Render PORT
    app.run(host='0.0.0.0', port=port)

# Flask serverni alohida oqimda ishga tushuramiz
Thread(target=run).start()

# Xabar yuboruvchi funksiya
async def send_ad():
    try:
        bot = Bot(token=BOT_TOKEN)
        message = "🚖 Ishtirxon Taxi - Toshkent-Samarqand-Farg'ona\n⏰ 8:00 dan\n📞 +998901234567"
        await bot.send_message(chat_id=CHANNEL_ID, text=message, parse_mode="HTML")
        print(f"✅ Xabar yuborildi: {message[:30]}...")
    except Exception as e:
        print(f"❌ Xato: {e}")

# Scheduler sozlash
scheduler = AsyncIOScheduler(timezone=TIMEZONE)
scheduler.add_job(send_ad, 'interval', minutes=1)

# Asosiy asyncio tsikli
async def main():
    scheduler.start()  # to‘g‘ri joyi shu
    print("🤖 Bot ishga tushdi! Xabarlar har 1 daqiqada yuboriladi...")
    while True:
        await asyncio.sleep(1)

# Ishga tushirish
try:
    loop = asyncio.get_event_loop()
    if loop.is_running():
        loop.create_task(main())
    else:
        loop.run_until_complete(main())
except KeyboardInterrupt:
    print("⛔️ Bot to'xtatildi")
    scheduler.shutdown()


