# -*- coding: utf-8 -*-
"""Reklama bot11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ICnDPNG4o-7TJzjlzFb3mQ7R2Hm_NAH
"""

!pip uninstall python-telegram-bot -y
!pip install python-telegram-bot==20.3



!pip install python-telegram-bot==20.3 apscheduler pytz
!pip install flask

import asyncio
from telegram import Bot
from apscheduler.schedulers.asyncio import AsyncIOScheduler
import pytz
from threading import Thread
from flask import Flask

# Sozlamalar
BOT_TOKEN = "7634842711:AAFa8U3t0x3YYulaty4grX560JyAsBi7re4"
CHANNEL_ID = "@servicyozyovon"  # O'zgartiring
TIMEZONE = pytz.timezone('Asia/Tashkent')

# Flask server - yangi portda (5000)
app = Flask(__name__)
@app.route('/')
def home(): return "Bot ishlayapti (5000-port)"

def run_flask():
    app.run(host='0.0.0.0', port=5000)

Thread(target=run_flask).start()

# Bot funktsiyalari
async def send_ad():
    try:
        bot = Bot(token=BOT_TOKEN)
        message = "🚖 Ishtirxon Taxsi - Toshkent-Samarqand-Farg'ona\n⏰ 8:00 dan\n📞 +998901234567"
        await bot.send_message(chat_id=CHANNEL_ID, text=message, parse_mode="HTML")
        print(f"✅ Xabar yuborildi: {message[:30]}...")
    except Exception as e:
        print(f"❌ Xato: {e}")

# Scheduler
scheduler = AsyncIOScheduler(timezone=TIMEZONE)
scheduler.add_job(send_ad, 'interval', minutes=1)
scheduler.start()

# Asosiy tsikl
async def main():
    print("🤖 Bot ishga tushdi! Xabarlar har 1 daqiqada yuboriladi...")
    while True:
        await asyncio.sleep(1)

# Ishga tushirish
try:
    loop = asyncio.get_event_loop()
    if loop.is_running():
        loop.create_task(main())
    else:
        loop.run_until_complete(main())
except KeyboardInterrupt:
    print("Bot to'xtatildi")
    scheduler.shutdown()

# Flask asosida ishlash uchun
from flask import Flask
app = Flask(__name__)

@app.route('/')
def home():
    return "Bot ishlayapti"



